titles:
  en: "Tasks",
  ru: "Задачи"
columns:
  title:
    type: string
    title: Title
  status:
    type: string
    title: Status
    fk: statuses
views:
  tag_$(tags):
    formats:
      - md
    columns:
      - title:
      - status:
  status_$(status):
    formats:
      - md
    columns:
      - title:
      - tags:
